CREATE DATABASE DesafioFIAP

CREATE TABLE TB_ALUNOS (
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	USUARIO VARCHAR(45) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	IsAtivo BIT NOT NULL DEFAULT 1,
)

CREATE TABLE TB_TURMAS (
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	CURSO_ID INT NOT NULL,
	NOMETURMA VARCHAR(45) NOT NULL,
	ANO VARCHAR(4) NOT NULL,
	IsAtivo BIT NOT NULL DEFAULT 1,
)

CREATE TABLE TB_ALUNOS_TURMAS (
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	ALUNO_ID INT FOREIGN KEY REFERENCES TB_ALUNOS(ID),
	TURMA_ID INT FOREIGN KEY REFERENCES TB_TURMAS(ID),
	IsAtivo BIT NOT NULL DEFAULT 1
)